<?php

namespace app\controller;

use think\Controller;

class Index extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        echo 'init';
    }

    public function index(){
        return '单一模块s';
    }

    public function arr(){
        $data = array('a'=>1,'b'=>2,'c'=>3);
        return json($data);
    }

    public function test(){
        return view();
    }
}